# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box="my-default"

  (1..3).each do |i|
    config.vm.define "master-#{i}" do |node|
      node.vm.hostname="master-#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{10+i}"
    end
  end

  (1..4).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname="node-#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{20+i}"
    end
  end

  (1..3).each do |i|
    config.vm.define "storager-#{i}" do |node|
      node.vm.hostname="storager-#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{30+i}"
    end
  end

end
